Cadastro de novo usuario
oyurimatheus/nosso-mercado-livre pull request #1
Opened 2020-04-13 22:17 UTC by oyurimatheus

2020-04-14 02:43 UTC, asouza requested changes

2020-04-14 02:43 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +                @NotNull Password password) {
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*
Belo uso do Password aqui. Facilita a vida de quem vai chamar a api.

2020-04-14 02:43 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/Password.java
> +    Password(@NotNull String password) {
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

Como saber se esse password é plain ou encoded? Nem a classe nem o construtor deixam nenhuma dica :).

2020-04-14 02:43 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +    public boolean equals(Object o) {
O equals flerta muito com o negócio. Quem decide quando duas coisas são iguais é justamente quem pediu a feature :). Neste caso em específico, dois usuários são iguais se eles tem o mesmo email.

2020-04-14 02:43 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +    public Long getId() {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Por que temos esses getters aqui?

2020-04-14 02:43 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/UserController.java
> +        var user = converter.convert(newUser);
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho. Uma leitura simples e que introduz bem o assunto https://www.sonarsource.com/resources/white-papers/cognitive-complexity.html*

Pq precisamos de um converter aqui quando já temos o request com todos os dados para criar um User?

2020-04-14 23:23 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +                @NotNull Password password) {
Obrigado 😄

2020-04-14 23:28 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/Password.java
> +    Password(@NotNull String password) {
Acha que colocar o nome do parâmetro como `rawPassword` já ajuda? Daria para colocar um método estático, algo como `Password.encode(rawPassword)`, o que acha?

2020-04-14 23:30 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +    public boolean equals(Object o) {
Faz sentido

2020-04-15 00:06 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/User.java
> +    public Long getId() {
[A JPA pede os getters na especificação](https://docs.jboss.org/hibernate/orm/5.0/mappingGuide/en-US/html/ch02.html#domainmodel-pojo-accessors) né? Mas com o Hibernate não precisam ser declarados, verdade

2020-04-15 00:09 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/users/UserController.java
> +        var user = converter.convert(newUser);
Realmente, nesse caso não precisa encapsular essa lógica em uma nova classe

2020-04-15 02:50 UTC, merged