Detalhe produto
oyurimatheus/nosso-mercado-livre pull request #10
Opened 2020-05-04 23:20 UTC by oyurimatheus

2020-05-05 09:04 UTC, asouza requested changes

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/categories/Category.java
> +    public Category getSuperCategory() {
*Não retornamos nulo dentro das regras da aplicação. Pense que seu computador vai explodir.*

E se não tiver categoria mãe?

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/categories/Category.java
> +    public Category getSuperCategory() {
Ou, você pode colocar uma asserção soltando illegalstate caso esse método seja invocado numa categoria sem mãe.

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/Product.java
> +    public List<Question> getQuestionsFromNewest() {
Aqui eu até estou bolando minha explicação final, então vai com a que eu tenho neste momento :). 

Este código é condizente com a orientação a objetos, sem dúvida, você junta estado e comportamento. Por outro lado lógicas de transformação e ordenação podem vir em diferentes sabores e de diferentes pontos de exibição. E o motivo dessa necessidade me faz pensar que você pode ter uma explosão de métodos que operam sobre o estado só pq você precisa ordenar e transformar de n formas. 

Então a minha sugestão é que você ou deixe o critério de ordenação para o ponto do código que quer exibir ordenado ou receba a função de ordenação como argumento. Pq você faz com que o ponto do código do código decida o critério de ordenação sobre sua coleção. Uma outra sugestão é fazer com que o estado normal do objeto seja uma coleção ordenada de questões. Você pode usar a interface SortedSet para declarar o atributo, usar a anotação de ordenação e implementar comparable na Question.

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/Product.java
> +    public BigDecimal rating() {
Já a operação de média realmente tem uma lógica sobre o estado. E uma que não é super genérica de cara... Acho que isso é o que diferencia muito, sabe? Enquanto que ordenar e transformar já nascem suportando um método genérico, o calculo da média não. Aí faz mais sentido a média está realmente dentro do objeto.

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsResponse.java
> +    private List<String> makeCategoryHierarchy(Category category) {
Pq você optou deixar o método de ordenação e rating dentro do produto e o método que retorna uma hierarquia de categoria do lado de fora da Categoria? O que a coitada da categoria fez para você :P?

2020-05-05 09:04 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsController.java
> +        return ok(new ProductDetailsResponse(possibleProduct.get(), uriComponentsBuilder));
Aqui faltou só retornar mais anuncios do vendedor.

2020-05-05 11:27 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsResponse.java
> +    private List<String> makeCategoryHierarchy(Category category) {
Eu fiquei pensando nisso haha, mas como só queria o nome das categorias pra montar a página, eu achei que seria melhor deixar essa lógica fora. Se ela ficar dentro de categoria, eu posso retornar a lista de categorias e montar a lista baseada no nome... acho que vale

2020-05-05 11:34 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/Product.java
> +    public List<Question> getQuestionsFromNewest() {
Faz sentido, faz sentido... Quando eu comecei a fazer o código, eu queria já retornar os dados do banco na ordem certa, acho que até por questão de performance seria melhor, porque não precisaria carregar a lista inteira e operá-la em memória.

Acho que nesse caso, como essa ordenação está muito ligada na view, acho que se ficar no lugar que tá montando a response faz mais sentido, ou então usar a `SortedSet` e já retornar na ordem das mais recentes primeiro

2020-05-05 11:46 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/categories/Category.java
> +    public Category getSuperCategory() {
Acho que nesse caso um `Optional` resolveria bem... A ideia da exceção é legal, mas aí a pessoa que usaria a API teria sempre que chamar um `hasSuperCategory` para não tomar um erro em execução

2020-05-05 11:47 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsController.java
> +        return ok(new ProductDetailsResponse(possibleProduct.get(), uriComponentsBuilder));
Verdade! Me esqueci

2020-05-06 09:54 UTC, asouza requested changes

2020-05-06 09:54 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsController.java
> +        return ok(new ProductDetailsResponse(product, productsByUser, uriComponentsBuilder));
*usar o mesmo valor duas vezes em um fluxo*

Esse código levanta um smell de consistência para mim. Nesse construtor você pode passar uma lista de produtos que não tem nada a ver com o produto em questão. E o padrão que eu já percebi é esse aqui: você precisou acessar a referência ```product``` duas vezes no mesmo fluxo. Na hora de montar os produtos do usuário e na hora de montar a response :). Você abre porta para inconsistência.

2020-05-06 09:54 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsResponse.java
> +    ProductDetailsResponse(Product product, List<Product> sellerOtherProducts, UriComponentsBuilder uriBuilder) {
Sacou, pode ser qualquer seller e não é isso que você quer.

2020-05-06 16:41 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/ProductDetailsResponse.java
> +    ProductDetailsResponse(Product product, List<Product> sellerOtherProducts, UriComponentsBuilder uriBuilder) {
Faz sentido! Fiz com que o próprio produto retorne essa lista de outros produtos do mesmo vendedor, acho que faz sentido ele saber disso...

2020-05-07 23:26 UTC, asouza requested changes
Só troca o equals e pode aprovar direto :)

2020-05-07 23:26 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/Product.java
> +        if (this == o) return true;
O equals deve ser implementado em cima de informação natural do objeto, na maioria das vezes a implementação dele devia ser decidida junto com quem entende do domínio. Quem melhor para falar que dois produtos são iguais?  

Pode usar a descrição + nome como equals aqui :). A gente deveria ter um número específico gerado no construtor para criar essa identificação.

2020-05-08 15:11 UTC, merged