Finaliza compra parte 2
oyurimatheus/nosso-mercado-livre pull request #12
Opened 2020-05-19 18:59 UTC by oyurimatheus

2020-05-19 20:01 UTC, asouza requested changes
Yuri seu código é bem bom. Eu estou subindo bastante a régua no seu review :).

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/products/Product.java
> +     * @param newPurchase a new Purchase (this parameter is highly coupled, but if needed an interface can be created to decouple)
fino

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/InvoiceClient.java
> +    @RequestMapping(method = POST, value = "/register/", produces = "application/json")
produces ou consumes? pergunto pq o retorno do método é void.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Payment.java
> +    private String status;
*Protegemos as bordas do sistema como se não houvesse amanhã.*

Como você garante a restrição do status aqui? Pq qualquer String pode entrar.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGateway.java
> +            if (payment.getStatus().equals("1")) {
*Operações sobre dados cujo tipo é padrão da linguagem devem ficar dentro das nossas classes.*

Aqui eu estou sendo minha versão mais chata, ok?

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGateway.java
> +            if (payment.getStatus().equals("1")) {
E se você quisesse ainda podia ser um pouco mais criativo :). A classe Payment pode ter um método statusToPaypal(), statusToPagseguro() etc. Aí o método status da enum vai saber qual método do payment invocar :). Só uma sugestão.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGateway.java
> +            return Status.valueOf(payment.getStatus());
Aqui é um acoplamento semântico super frágil. Indepentende de onde via residir o código, tanto aqui quanto o paypal merecem um checagem de condição antes de executar a lógica.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +            var bindException = new BindException(new Object(), "");
Espertinho :). Esse é um código que é bem de infra e tem tudo para ser super ortogonal. como você pode fazer para simplificar a utilização da api?

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        Payment payment = paymentReturn.toPayment();
Como você pode ter um payment se ainda nem foi processada a transação? Nesse exato momento o seu Payment tem zero transações associadas e essa é uma situação que devemos evitar. Pense que todo pagamento, em qualquer momento do tempo, possui pelo menos uma transação associada. Ou o pagamento já é a transação? Pelo código não parece, já que você passa o payment para process.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        purchase.process(payment);
Aqui parece que você precisa de um objeto de transição. Processar o pagamento parece gerar um estado novo no sistema. O meu chute, vendo só essa parte do código,  é que você precisa processar isso antes de publicar o evento pq você vai querer ter acesso a algum estado que foi alterado lá dentro. Se isso for verdade, tem um acoplamento que só você enxerga e que seria complicado para outra pessoa inferir. Se você cria um objeto de transição, isso fica nítido.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Purchase.java
> +        if (SUCESSO == status) {
Ter uma variável de controle é ok e resolve. Só que é mais um estado pra você controlar. Pq não verificar se dentro do paymentAttempts não um pagamento completado com sucesso? Aqui você abre porta para bug, já que você tem o controle sobre um conjunto de objetos fora do conjunto.

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Purchase.java
> +                .filter(payment -> paymentGateway.status(payment) == SUCESSO)
acho que aqui eu viajei... pq o status não está dentro do payment? Ah, aquela classe Payment é de domínio mesmo. Então eu sugiro que você refatore e faça ela ter o status amarrado com o domínio. Os status virem em formas diferentes não pode residir no domínio. Tudo fica muito frágil. No sistema é erro ou sucesso :).

2020-05-19 20:01 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/SuccessPurchaseListener.java
> +    private final Set<PostSuccessPurchaseAction> postSuccessPurchaseActions;
Fino. Mas eu tenho uma pergunta... pq você simplesmente não recebe um objeto dessa classe injetado no controller e chama o método? Pergunto isso pq a implementação de listener deixa o código completamente desacoplado e do jeito que eu enxergo, regras de negócio devem ter o mínimo de acoplamento. Por isso que elas formam um fluxo.

2020-05-19 21:48 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/InvoiceClient.java
> +    @RequestMapping(method = POST, value = "/register/", produces = "application/json")
Acho que nesse caso é `produces`, porque ele está enviando os dados nesse formato...

2020-05-20 16:37 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Purchase.java
> +        if (SUCESSO == status) {
É porque nesse caso eu pensei que existia o status da compra e o status do pagamento, o que daria para fazer seria conferir os dois status sempre?

2020-05-20 17:48 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Purchase.java
> +        if (SUCESSO == status) {
Poderíamos ter isso que falou, coisas como "despachada, recebida etc..." nesse momento não temos, vai ficar para a próxima! Quando falamos do status realmente é sobre o estado dos pagamentos.. precisa de pelo menos que deu certo.

2020-05-21 01:17 UTC, asouza approved these changes
Acho que o código está super bom. Único ponto de atenção, você tem 4 ifs espalhados nas ações pós compra. Se você olhar, a carga intrínseca do sistema como um todo fica até maior :). Pq você poderia ter dois ifs combinados com 2 interfaces(sucesso e erro) + as mesmas 4 implementações. Já nas implementações você teria as checagens de pré-condições(processador de sucesso só pode ser chamado para pagamento com sucesso e tal). Só uma reflexão.

2020-05-21 01:17 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGateway.java
> +            return payment.payPalStatus();
Esse código é bem legal... pq ele é fácil e complexo(olha eu brincando com as palavras... só entre a gente ). Fácil, pq é uma linha... Complexo pq você precisa manjar de orientação a objetos para chegar na conclusão de delegar a chamada para um método de um objeto que você tem mãos para outro ponto. Quem chama o método status, já tem um PaymentReturn em mãos e poderia mandar o if da massa... Aí você vem e passa como argumento para deixar uma outra implementação decidir... é inspirado no chamado double dispatch(https://en.wikipedia.org/wiki/Double_dispatch)

2020-05-21 01:17 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        PostPaymentProcessedPurchase postPaymentPurchase = purchase.process(paymentReturn);
Aí você ganha meu coração! Esses objetos de transição fazem bastante sentido... e inclusive, se você olhar para a suposta invenção do cara de 10 anos atrás, eles seriam seus eventos em um command do cqrs né? Só que aqui é orientação objeto simlpes e pura. Simplesmente pq estamos usando os conceitos escritos na definição da coisa.

2020-05-21 01:17 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        postPurchaseActions.forEach(action -> action.execute(postPaymentPurchase, uriBuilder));
Aqui ficou com 6 pontos de carga intrínseca e está tudo certo. A parte boa é que se apertasse, o código do foreach naturalmente poderia virar um ```acoes.executa(postPaymentPurchase)```  :).

2020-05-21 01:17 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/Purchase.java
> +        paymentAttempts.add(new Payment(paymentReturn.getPaymentId(), paymentStatus));
Aqui você poderia checar a pré condição...  pq se esse paymentstatus é sucesso, isPaymentSuccessful() tinha que retornar false.

2020-05-21 01:31 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGateway.java
> +            return payment.payPalStatus();
Verdade! Eu lembro que aprendi esse pattern com o Sensei haha

2020-05-21 01:33 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        PostPaymentProcessedPurchase postPaymentPurchase = purchase.process(paymentReturn);
E esses objetos fazem muito sentido para a gente criar um fluxo na aplicação, só que eles aumentam a carca intrínseca do método né?

2020-05-21 01:34 UTC, oyurimatheus commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        postPurchaseActions.forEach(action -> action.execute(postPaymentPurchase, uriBuilder));
Poderia ter um Service né para encapsular essas chamadas? E nele ter o `if` para o caso de sucesso e de falha

2020-05-21 09:08 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        PostPaymentProcessedPurchase postPaymentPurchase = purchase.process(paymentReturn);
Aumentam, sem dúvida. A troca nesse caso é pela consistência dentro do código. Você quer aumentar as chances da próxima chamada ser executada em cima de um estado consistente. Com o tempo a gente vai avaliando a hipótese.

2020-05-21 09:09 UTC, asouza commented on src/main/java/me/oyurimatheus/nossomercadolivre/purchase/PaymentGatewayReturnController.java
> +        postPurchaseActions.forEach(action -> action.execute(postPaymentPurchase, uriBuilder));
Poderia, ou poderia ficar aqui. Ficaria em 7 pontos, se não me engano.

2020-07-31 14:32 UTC, merged